### ISSUE TITLE
Is there a demo or screenshot of this product?

### ISSUE THREAD

**Issue by hitinder** [avcomps/Restix#1]
Hello Ali, @avcomps 
I was wondering if there is any demo or screenshot of this product.

**Comment by avcomps** [comment]
Hey hitinder, thanks for your answer. As I redesigned on a last phase all the UI, I haven't uploaded any screenshot, but I will do it very soon, possibly on this week. Nevertheless, feel free to execute the program by using the "Restix.exe" located on the /bin/Debug/ folder. You won't be disappointed :) 

PD: the only bad point is that I haven't embedded the Montserrat font to the project, so when you gonna run the program it will use the default Windows font.

**Comment by avcomps** [comment]
hey @hitinder , finally I just uploaded some screenshots. Make sure you check them out 👍
